language: python
sudo: false
python:
  - "2.7"
addons:
  apt:
    packages:
    - libgdal1h
    - gdal-bin
    - libgdal-dev
install:
  - pip install -r requirements.txt
script: "python tests/test_msr_utility.py"
